### ISSUE TITLE
JPEG XS has no hyphen

### ISSUE THREAD

**Issue by mpeg2tom** [OpenVisualCloud/SVT-JPEG-XS#1]
The title of [ISO/IEC 21122-1:2022](https://www.iso.org/standard/81551.html) is "JPEG XS low-latency lightweight image coding system".  There is no hyphen in JPEG XS.

**Comment by mpeg2tom** [comment]
If the hyphen is just the project name, I understand.  But if you are open to it, I could do a PR to remove the hyphen in the documentation.

**Comment by ttrigui** [comment]
@mpeg2tom , please feel free to rename it in the documentation. thank you
